### 마일스톤 생성
POST http://localhost:8082/projects/1/milestones
Content-Type: application/json

{
  "name": "기획 완료",
  "status": "START"
}

### 모든 마일스톤 조회
GET http://localhost:8082/projects/1/milestones

### 특정 마일스톤 조회
GET http://localhost:8082/projects/1/milestones/1

### 마일스톤 수정
POST http://localhost:8082/projects/1/milestones/1/update
Content-Type: application/json

{
  "name": "기획 및 설계 완료",
  "status": "PROGRESS"
}


### 마일스톤 삭제
POST http://localhost:8082/projects/1/milestones/1/delete

